### ISSUE TITLE
Code Examples Are White.

### ISSUE THREAD

**Issue by RobinRumpunen** [SmorcIRL/Unity-Documentation-Dark-Theme#1]
If you are using the Unity Documentation for version 2019.2 all code example backgrounds are still white.

I solved it by adding !important to pre, pre code.
Like this:
`pre,
pre code {
    color: #fff;
    background-color: #161616 !important;
}`
I may also have changed the background-color to what is shown above, don't remember.

Would be good to change this so that the theme isn't broken for others.
Thanks!

**Comment by SmorcIRL** [comment]
Updated as you wrote. Thanks for the info!
